In [240]:
import pandas as pd

In [241]:
employee_data = pd.read_csv('./data/employees.csv')
projects=pd.read_csv('./data/projects.csv')

In [242]:
employee_data.head()

,employee_id,first_name,last_name,email,department,role,location,hire_date,salary,status,performance_score,years_experience,certifications
0,770487,Alex,Walker,emp770487@nexaworks.io,Product,Product Manager,New York,2023-04-26,127097,Terminated,3.4,3,GCP
1,133326,Nina,Brown,emp133326@nexaworks.io,Engineering,Software Engineer,London,2017-06-14,115990,Active,3.8,21,CISSP
2,539898,Fatima,Thompson,emp539898@nexaworks.io,Marketing,Brand Manager,Singapore,2021-08-10,127926,Terminated,3.4,9,AWS
3,325772,Yuki,Young,emp325772@nexaworks.io,Finance,Financial Analyst,New York,2016-01-15,154595,Contract,3.3,9,PMP
4,865179,Yuki,Hall,emp865179@nexaworks.io,Operations,Operations Analyst,Berlin,2019-03-31,75656,Contract,2.2,7,Scrum Master

In [ ]:
employee_data.isna().sum()  #sum of all the null values in each column

employee_id            0
first_name             0
last_name              0
email                  0
department             0
role                   0
location               0
hire_date              0
salary                 0
status                 0
performance_score      0
years_experience       0
certifications       151
dtype: int64

In [ ]:
employee_data['pm_name'] = employee_data['first_name'].str.cat(employee_data['last_name'], sep=' ') 
# Create a new column 'pm_name' by concatenating 'first_name' and 'last_name' with a space separator

In [ ]:
projects.head() # Display the first few rows of the projects DataFrame

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.4,3.4,APAC,Yes
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.1,NaN,Europe,Yes
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,NaN,NaN,North America,Yes
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.0,NaN,North America,No
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.9,NaN,North America,Yes

# Handling Null values

In [246]:
projects

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.4,3.4,APAC,Yes
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.1,NaN,Europe,Yes
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,NaN,NaN,North America,Yes
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.0,NaN,North America,No
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.9,NaN,North America,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,477114,354801,5,14.5,3.3,North America,Yes
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,443897,925622,25,39.6,4.6,APAC,Yes
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,592972,725113,22,47.5,4.8,Europe,Yes
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,148174,882032,14,46.7,4.0,Middle East,No
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,101773,658065,22,19.2,NaN,LATAM,Yes

In [ ]:

projects.fillna(projects['avg_velocity'].mean(), inplace=True) 
# Fill missing values in the 'avg_velocity' column with the mean of that column

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.400000,3.400000,APAC,Yes
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.100000,37.678676,Europe,Yes
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,37.678676,37.678676,North America,Yes
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.000000,37.678676,North America,No
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.900000,37.678676,North America,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,477114,354801,5,14.500000,3.300000,North America,Yes
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,443897,925622,25,39.600000,4.600000,APAC,Yes
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,592972,725113,22,47.500000,4.800000,Europe,Yes
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,148174,882032,14,46.700000,4.000000,Middle East,No
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,101773,658065,22,19.200000,37.678676,LATAM,Yes

In [ ]:
projects['client_satisfaction'].isna().sum()
# Check for missing values in the 'client_satisfaction' column

np.int64(0)

In [249]:
projects.dtypes

project_id               int64
project_name               str
project_type               str
client                     str
priority                   str
status                     str
start_date                 str
end_date                   str
budget_usd               int64
actual_spend_usd         int64
project_manager_id       int64
tech_lead_id             int64
team_size                int64
avg_velocity           float64
client_satisfaction    float64
region                     str
billable                   str
dtype: object

In [ ]:
projects['start_date']=pd.to_datetime(projects['start_date']) # Convert the 'start_date' column to datetime format
projects['end_date']=pd.to_datetime(projects['end_date']) # Convert the 'end_date' column to datetime format

In [251]:
projects.dtypes

project_id                      int64
project_name                      str
project_type                      str
client                            str
priority                          str
status                            str
start_date             datetime64[us]
end_date               datetime64[us]
budget_usd                      int64
actual_spend_usd                int64
project_manager_id              int64
tech_lead_id                    int64
team_size                       int64
avg_velocity                  float64
client_satisfaction           float64
region                            str
billable                          str
dtype: object

In [252]:
projects['actual_spend_usd']

0        30295
1       724953
2         3820
3       593010
4       195624
         ...
1495     17414
1496     51539
1497     33895
1498    785690
1499     12516
Name: actual_spend_usd, Length: 1500, dtype: int64

In [ ]:
projects['outlier_budget'] = projects['actual_spend_usd'] > projects['budget_usd'] * 1.15 
# Create a new column 'outlier_budget' that is True if 'actual_spend_usd' is greater than 115% of 'budget_usd', otherwise False

In [254]:
projects

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.400000,3.400000,APAC,Yes,False
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.100000,37.678676,Europe,Yes,False
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,37.678676,37.678676,North America,Yes,False
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.000000,37.678676,North America,No,False
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.900000,37.678676,North America,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,477114,354801,5,14.500000,3.300000,North America,Yes,False
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,443897,925622,25,39.600000,4.600000,APAC,Yes,False
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,592972,725113,22,47.500000,4.800000,Europe,Yes,False
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,148174,882032,14,46.700000,4.000000,Middle East,No,False
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,101773,658065,22,19.200000,37.678676,LATAM,Yes,False

In [ ]:
projects[['actual_spend_usd', 'budget_usd', 'outlier_budget']]
# Display the 'actual_spend_usd', 'budget_usd', and 'outlier_budget' columns to verify the new column's values

      actual_spend_usd  budget_usd  outlier_budget
0                30295       57562           False
1               724953      726154           False
2                 3820      169982           False
3               593010      638324           False
4               195624      557186           False
...                ...         ...             ...
1495             17414       18311           False
1496             51539       69080           False
1497             33895       60029           False
1498            785690     1040111           False
1499             12516       12004           False

[1500 rows x 3 columns]

In [ ]:
projects['budget_threshold'] = projects['budget_usd'] * 1.15

# Display the 'budget_usd', 'budget_threshold', and 'outlier_budget' columns to verify the new column's values

In [ ]:
projects[['actual_spend_usd', 'budget_usd', 'budget_threshold', 'outlier_budget']]

# Display the 'actual_spend_usd', 'budget_usd', 'budget_threshold', and 'outlier_budget' columns to verify the new column's values

      actual_spend_usd  budget_usd  budget_threshold  outlier_budget
0                30295       57562          66196.30           False
1               724953      726154         835077.10           False
2                 3820      169982         195479.30           False
3               593010      638324         734072.60           False
4               195624      557186         640763.90           False
...                ...         ...               ...             ...
1495             17414       18311          21057.65           False
1496             51539       69080          79442.00           False
1497             33895       60029          69033.35           False
1498            785690     1040111        1196127.65           False
1499             12516       12004          13804.60           False

[1500 rows x 4 columns]

In [258]:
employee_data.head()

,employee_id,first_name,last_name,email,department,role,location,hire_date,salary,status,performance_score,years_experience,certifications,pm_name
0,770487,Alex,Walker,emp770487@nexaworks.io,Product,Product Manager,New York,2023-04-26,127097,Terminated,3.4,3,GCP,Alex Walker
1,133326,Nina,Brown,emp133326@nexaworks.io,Engineering,Software Engineer,London,2017-06-14,115990,Active,3.8,21,CISSP,Nina Brown
2,539898,Fatima,Thompson,emp539898@nexaworks.io,Marketing,Brand Manager,Singapore,2021-08-10,127926,Terminated,3.4,9,AWS,Fatima Thompson
3,325772,Yuki,Young,emp325772@nexaworks.io,Finance,Financial Analyst,New York,2016-01-15,154595,Contract,3.3,9,PMP,Yuki Young
4,865179,Yuki,Hall,emp865179@nexaworks.io,Operations,Operations Analyst,Berlin,2019-03-31,75656,Contract,2.2,7,Scrum Master,Yuki Hall

In [259]:
projects.head()

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.400000,3.400000,APAC,Yes,False,66196.3
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.100000,37.678676,Europe,Yes,False,835077.1
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,37.678676,37.678676,North America,Yes,False,195479.3
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.000000,37.678676,North America,No,False,734072.6
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.900000,37.678676,North America,Yes,False,640763.9

In [ ]:
employee_data['employee_id'].isin(projects['project_manager_id']).sum()

# Check how many employee IDs in the 'employee_id' column of employee_data are present in the 'project_manager_id' column of projects, and sum the total count

np.int64(441)

In [ ]:
records = pd.merge(employee_data, projects,left_on='employee_id',right_on='project_manager_id',how='outer')

# Merge the employee_data and projects DataFrames on the 'employee_id' and 'project_manager_id' columns using an outer join, and store the result in a new DataFrame called records

In [262]:
records.head()

,employee_id,first_name,last_name,email,department,role,location,hire_date,salary,status_x,...,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold
0,101773,Mei,Garcia,emp101773@nexaworks.io,Data,Data Engineer,San Francisco,2019-01-31,168062,Active,...,33052.0,101773.0,772580.0,12.0,48.200000,3.900000,LATAM,Yes,False,87910.60
1,101773,Mei,Garcia,emp101773@nexaworks.io,Data,Data Engineer,San Francisco,2019-01-31,168062,Active,...,12516.0,101773.0,658065.0,22.0,19.200000,37.678676,LATAM,Yes,False,13804.60
2,102260,Amara,Walker,emp102260@nexaworks.io,HR,People Ops Specialist,San Francisco,2023-10-17,174277,Terminated,...,56174.0,102260.0,138436.0,21.0,33.200000,37.678676,LATAM,No,False,75765.45
3,102260,Amara,Walker,emp102260@nexaworks.io,HR,People Ops Specialist,San Francisco,2023-10-17,174277,Terminated,...,81012.0,102260.0,952657.0,16.0,27.300000,4.300000,Europe,Yes,False,132086.70
4,107686,Kevin,Clark,emp107686@nexaworks.io,Product,Senior PM,New York,2022-07-08,110882,On Leave,...,7996.0,107686.0,219550.0,11.0,37.678676,37.678676,Middle East,Yes,False,124776.15

In [ ]:
no_projects = records[records['project_id'].isna() & records['employee_id'].notna()]

# Create a new DataFrame called no_projects that contains rows from records where 'project_id' is NaN and 'employee_id' is not NaN, indicating employees who are not project managers

In [ ]:
records['project_id'].isna().sum()

np.int64(59)

In [265]:
no_projects

,employee_id,first_name,last_name,email,department,role,location,hire_date,salary,status_x,...,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold
121,172222,Yuki,Robinson,emp172222@nexaworks.io,Data,Data Engineer,Sydney,2020-01-15,132508,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,173863,Ahmed,Garcia,emp173863@nexaworks.io,QA,Test Lead,Austin,2017-11-25,161858,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,178463,Nina,Martinez,emp178463@nexaworks.io,Operations,Ops Manager,Sydney,2018-10-18,159197,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,186686,Aisha,Walker,emp186686@nexaworks.io,QA,QA Engineer,San Francisco,2023-12-04,112810,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,196955,Liam,Hall,emp196955@nexaworks.io,Data,Data Engineer,New York,2015-07-31,125375,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,219346,Maria,Ali,emp219346@nexaworks.io,Finance,Finance Manager,London,2016-03-30,129251,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,243167,Kevin,Robinson,emp243167@nexaworks.io,Marketing,Brand Manager,Austin,2021-04-19,187497,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,253541,Noah,Garcia,emp253541@nexaworks.io,Engineering,Lead Engineer,New York,2017-04-15,196865,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,261712,Chen,Johnson,emp261712@nexaworks.io,HR,Recruiter,San Francisco,2023-04-18,157137,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,269834,Chen,Davis,emp269834@nexaworks.io,Finance,Senior Analyst,Dubai,2018-11-18,191025,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,293757,David,Müller,emp293757@nexaworks.io,Design,Visual Designer,Austin,2018-08-18,120024,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,296242,Layla,Ali,emp296242@nexaworks.io,Sales,Business Dev Rep,New York,2020-01-01,93962,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,296243,Fatima,Brown,emp296243@nexaworks.io,Data,Data Scientist,San Francisco,2017-08-29,125623,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,300051,Liam,Clark,emp300051@nexaworks.io,Engineering,Principal Engineer,New York,2018-07-08,164780,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,304110,Mei,Young,emp304110@nexaworks.io,Finance,Controller,San Francisco,2015-10-29,156279,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419,341162,Layla,Garcia,emp341162@nexaworks.io,Product,Product Director,New York,2017-05-16,94384,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,362035,Fatima,Ali,emp362035@nexaworks.io,Design,Visual Designer,San Francisco,2024-04-16,154184,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,398505,Noah,Young,emp398505@nexaworks.io,Data,Data Scientist,San Francisco,2019-08-19,104283,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,411847,James,Clark,emp411847@nexaworks.io,Marketing,Marketing Manager,New York,2015-07-23,157996,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,424620,Mei,Lewis,emp424620@nexaworks.io,Data,Analytics Manager,Sydney,2022-03-20,141108,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,437226,Carlos,Patel,emp437226@nexaworks.io,HR,People Ops Specialist,Dubai,2017-01-06,61832,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573,446922,Chen,Brown,emp446922@nexaworks.io,Finance,Senior Analyst,New York,2022-07-12,116481,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,464069,David,Johnson,emp464069@nexaworks.io,Data,Analytics Manager,New York,2022-06-02,152142,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,493396,Noah,Tanaka,emp493396@nexaworks.io,Operations,Operations Analyst,Toronto,2022-02-08,79404,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,493663,Aisha,Kim,emp493663@nexaworks.io,HR,Recruiter,Berlin,2022-08-16,208583,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,494609,Alex,Williams,emp494609@nexaworks.io,Marketing,Brand Manager,Berlin,2018-12-16,145448,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,506945,Daniel,Davis,emp506945@nexaworks.io,Operations,Scrum Master,Toronto,2015-07-10,65460,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
775,541557,Amara,Tanaka,emp541557@nexaworks.io,Sales,Solutions Engineer,San Francisco,2023-10-11,75164,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,570880,Marcus,Clark,emp570880@nexaworks.io,QA,Automation Engineer,London,2021-07-12,160068,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
813,572536,Sofia,Johnson,emp572536@nexaworks.io,Finance,Controller,Singapore,2022-10-11,208136,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,597923,Layla,Young,emp597923@nexaworks.io,Data,Data Analyst,Austin,2016-04-14,145703,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,600590,James,Thompson,emp600590@nexaworks.io,HR,HR Business Partner,New York,2015-06-04,194927,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
981,676680,Nina,Thompson,emp676680@nexaworks.io,HR,People Ops Specialist,Remote,2022-05-17,96465,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,683390,Ethan,Lewis,emp683390@nexaworks.io,HR,People Ops Specialist,Singapore,2018-02-05,191233,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,691240,Noah,Brown,emp691240@nexaworks.io,Marketing,Content Strategist,New York,2022-08-24,199205,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1033,699743,Chen,Chen,emp699743@nexaworks.io,Data,Data Engineer,San Francisco,2022-09-08,154806,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034,701334,Omar,Müller,emp701334@nexaworks.io,Data,Analytics Manager,Remote,2019-06-05,145474,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042,703656,Yuki,Hall,emp703656@nexaworks.io,HR,People Ops Specialist,Singapore,2024-05-30,100537,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1046,711680,Elena,Walker,emp711680@nexaworks.io,Finance,Financial Analyst,Berlin,2015-07-27,128755,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,725780,Sofia,Müller,emp725780@nexaworks.io,Sales,Account Executive,San Francisco,2024-05-03,105886,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1101,755993,Liam,Tanaka,emp755993@nexaworks.io,Sales,Sales Manager,Toronto,2019-10-25,78907,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1127,778818,Marcus,Davis,emp778818@nexaworks.io,Design,UX Designer,Berlin,2017-07-05,121162,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1148,789461,Carlos,Martinez,emp789461@nexaworks.io,QA,Quality Manager,Toronto,2020-08-26,155837,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1149,789880,Chen,Johnson,emp789880@nexaworks.io,Operations,Ops Manager,San Francisco,2015-07-21,151037,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1223,827369,Carlos,Thompson,emp827369@nexaworks.io,Operations,Ops Manager,Austin,2022-06-06,159976,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1288,865054,Chen,Kim,emp865054@nexaworks.io,Product,Product Director,New York,2019-10-15,136926,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,874568,Zara,Chen,emp874568@nexaworks.io,Engineering,Senior Engineer,Sydney,2019-09-08,101081,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1357,901909,Ethan,Clark,emp901909@nexaworks.io,Sales,Account Executive,Remote,2023-07-23,100925,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1358,903035,Carlos,Lewis,emp903035@nexaworks.io,Design,UI Designer,Remote,2022-05-26,179592,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1361,904214,Zara,Ali,emp904214@nexaworks.io,QA,Automation Engineer,San Francisco,2021-12-06,62939,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1373,909652,Amara,Patel,emp909652@nexaworks.io,Operations,Scrum Master,Austin,2022-05-21,209485,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1403,925622,Kevin,Ali,emp925622@nexaworks.io,Product,Associate PM,Austin,2015-06-08,178388,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1427,935457,Ryan,Hall,emp935457@nexaworks.io,Engineering,DevOps Engineer,Remote,2020-04-27,124607,Contract,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505,974190,Nadia,Nguyen,emp974190@nexaworks.io,Operations,Scrum Master,Austin,2018-02-19,63576,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1514,979562,Amara,Williams,emp979562@nexaworks.io,QA,Automation Engineer,Toronto,2020-09-13,101452,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1524,985506,Ahmed,Müller,emp985506@nexaworks.io,Product,Senior PM,Austin,2019-11-20,209369,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537,992400,Carlos,Chen,emp992400@nexaworks.io,Data,Analytics Manager,Toronto,2018-01-22,105544,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1557,997287,Nina,Hall,emp997287@nexaworks.io,Finance,Financial Analyst,Remote,2023-08-27,127340,On Leave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1558,997594,Ines,Williams,emp997594@nexaworks.io,HR,HR Business Partner,Austin,2018-07-27,178987,Terminated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [266]:
%pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
records[['employee_id','project_manager_id']]

# Display the 'employee_id' and 'project_manager_id' columns from the records DataFrame to verify the merge results

      employee_id  project_manager_id
0          101773            101773.0
1          101773            101773.0
2          102260            102260.0
3          102260            102260.0
4          107686            107686.0
...           ...                 ...
1554       995993            995993.0
1555       995993            995993.0
1556       995993            995993.0
1557       997287                 NaN
1558       997594                 NaN

[1559 rows x 2 columns]

In [ ]:

valid_keys = projects[projects['project_manager_id'].isin(employee_data['employee_id'])]

# Filter the projects DataFrame to include only rows where 'project_manager_id'
#  is present in the 'employee_id' column of employee_data, and store the result in a new DataFrame called
valid_keys

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.400000,3.400000,APAC,Yes,False,66196.30
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.100000,37.678676,Europe,Yes,False,835077.10
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,37.678676,37.678676,North America,Yes,False,195479.30
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.000000,37.678676,North America,No,False,734072.60
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.900000,37.678676,North America,Yes,False,640763.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,477114,354801,5,14.500000,3.300000,North America,Yes,False,21057.65
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,443897,925622,25,39.600000,4.600000,APAC,Yes,False,79442.00
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,592972,725113,22,47.500000,4.800000,Europe,Yes,False,69033.35
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,148174,882032,14,46.700000,4.000000,Middle East,No,False,1196127.65
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,101773,658065,22,19.200000,37.678676,LATAM,Yes,False,13804.60

In [269]:
projects['overrun_amount'] = projects['actual_spend_usd'] - projects['budget_usd']
projects['overrun_amount']
projects

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,project_manager_id,tech_lead_id,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold,overrun_amount
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,587274,232731,4,47.400000,3.400000,APAC,Yes,False,66196.30,-27267
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,137572,304110,3,46.100000,37.678676,Europe,Yes,False,835077.10,-1201
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,929130,952679,11,37.678676,37.678676,North America,Yes,False,195479.30,-166162
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,470248,681141,10,22.000000,37.678676,North America,No,False,734072.60,-45314
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,187949,560485,10,32.900000,37.678676,North America,Yes,False,640763.90,-361562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,477114,354801,5,14.500000,3.300000,North America,Yes,False,21057.65,-897
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,443897,925622,25,39.600000,4.600000,APAC,Yes,False,79442.00,-17541
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,592972,725113,22,47.500000,4.800000,Europe,Yes,False,69033.35,-26134
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,148174,882032,14,46.700000,4.000000,Middle East,No,False,1196127.65,-254421
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,101773,658065,22,19.200000,37.678676,LATAM,Yes,False,13804.60,512

In [270]:
projects['duration_days']=(projects['end_date']-projects['start_date']).dt.days
projects[['start_date','end_date','duration_days']]

     start_date   end_date  duration_days
0    2022-05-30 2022-12-11            195
1    2022-06-24 2023-06-08            349
2    2020-04-21 2020-09-22            154
3    2021-03-09 2021-07-21            134
4    2021-02-15 2022-04-25            434
...         ...        ...            ...
1495 2023-09-09 2025-01-11            490
1496 2023-06-19 2024-05-22            338
1497 2021-09-23 2023-01-20            484
1498 2022-06-28 2022-09-24             88
1499 2020-10-18 2021-03-15            148

[1500 rows x 3 columns]

### Overrun percentage

In [271]:
projects['overrun_pct']= projects['overrun_amount']/projects['budget_usd']*100
projects[['actual_spend_usd', 'budget_usd', 'overrun_amount', 'overrun_pct']]

      actual_spend_usd  budget_usd  overrun_amount  overrun_pct
0                30295       57562          -27267   -47.369793
1               724953      726154           -1201    -0.165392
2                 3820      169982         -166162   -97.752703
3               593010      638324          -45314    -7.098903
4               195624      557186         -361562   -64.890719
...                ...         ...             ...          ...
1495             17414       18311            -897    -4.898695
1496             51539       69080          -17541   -25.392299
1497             33895       60029          -26134   -43.535624
1498            785690     1040111         -254421   -24.460947
1499             12516       12004             512     4.265245

[1500 rows x 4 columns]

In [272]:
projects

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,...,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold,overrun_amount,duration_days,overrun_pct
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,...,4,47.400000,3.400000,APAC,Yes,False,66196.30,-27267,195,-47.369793
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,...,3,46.100000,37.678676,Europe,Yes,False,835077.10,-1201,349,-0.165392
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,...,11,37.678676,37.678676,North America,Yes,False,195479.30,-166162,154,-97.752703
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,...,10,22.000000,37.678676,North America,No,False,734072.60,-45314,134,-7.098903
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,...,10,32.900000,37.678676,North America,Yes,False,640763.90,-361562,434,-64.890719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,...,5,14.500000,3.300000,North America,Yes,False,21057.65,-897,490,-4.898695
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,...,25,39.600000,4.600000,APAC,Yes,False,79442.00,-17541,338,-25.392299
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,...,22,47.500000,4.800000,Europe,Yes,False,69033.35,-26134,484,-43.535624
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,...,14,46.700000,4.000000,Middle East,No,False,1196127.65,-254421,88,-24.460947
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,...,22,19.200000,37.678676,LATAM,Yes,False,13804.60,512,148,4.265245

In [273]:
total_spend=projects['actual_spend_usd'].sum()

In [274]:
total_budget=projects['budget_usd'].sum()

## TOTAL PROFIT

In [275]:
total_profit = total_budget - total_spend
total_profit_formatted = f"{total_profit:,}"
total_profit_formatted

'158,974,428'

In [276]:
projects

,project_id,project_name,project_type,client,priority,status,start_date,end_date,budget_usd,actual_spend_usd,...,team_size,avg_velocity,client_satisfaction,region,billable,outlier_budget,budget_threshold,overrun_amount,duration_days,overrun_pct
0,699083,Delta Systems – API Integration,API Integration,Frontier AI,Medium,Completed,2022-05-30,2022-12-11,57562,30295,...,4,47.400000,3.400000,APAC,Yes,False,66196.30,-27267,195,-47.369793
1,907069,OmegaRetail – Cloud Migration,Cloud Migration,NovaCare,High,In Progress,2022-06-24,2023-06-08,726154,724953,...,3,46.100000,37.678676,Europe,Yes,False,835077.10,-1201,349,-0.165392
2,818651,Apex Corp – AI/ML Model,AI/ML Model,Frontier AI,High,Planning,2020-04-21,2020-09-22,169982,3820,...,11,37.678676,37.678676,North America,Yes,False,195479.30,-166162,154,-97.752703
3,571923,Cornerstone Inc – ERP Implementation,ERP Implementation,LumaMedia,Critical,In Progress,2021-03-09,2021-07-21,638324,593010,...,10,22.000000,37.678676,North America,No,False,734072.60,-45314,134,-7.098903
4,711324,Apex Corp – Marketing Campaign,Marketing Campaign,HorizonBank,Critical,In Progress,2021-02-15,2022-04-25,557186,195624,...,10,32.900000,37.678676,North America,Yes,False,640763.90,-361562,434,-64.890719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,113914,Frontier AI – ERP Implementation,ERP Implementation,Keystone Partners,Low,Completed,2023-09-09,2025-01-11,18311,17414,...,5,14.500000,3.300000,North America,Yes,False,21057.65,-897,490,-4.898695
1496,561350,Elevate Health – Web Platform,Web Platform,Apex Corp,Medium,Completed,2023-06-19,2024-05-22,69080,51539,...,25,39.600000,4.600000,APAC,Yes,False,79442.00,-17541,338,-25.392299
1497,633830,BlueSky Ltd – Marketing Campaign,Marketing Campaign,Meridian Group,Medium,Completed,2021-09-23,2023-01-20,60029,33895,...,22,47.500000,4.800000,Europe,Yes,False,69033.35,-26134,484,-43.535624
1498,779662,LumaMedia – AI/ML Model,AI/ML Model,Apex Corp,Critical,Completed,2022-06-28,2022-09-24,1040111,785690,...,14,46.700000,4.000000,Middle East,No,False,1196127.65,-254421,88,-24.460947
1499,572209,Elevate Health – Product Launch,Product Launch,Frontier AI,Low,On Hold,2020-10-18,2021-03-15,12004,12516,...,22,19.200000,37.678676,LATAM,Yes,False,13804.60,512,148,4.265245

## Top Pms by client satisfaction

In [277]:
records.groupby(['department','region','priority']).agg({'client_satisfaction':'mean'}).reset_index()

    department         region  priority  client_satisfaction
0         Data           APAC  Critical            20.989338
1         Data           APAC      High            37.678676
2         Data           APAC       Low            24.440724
3         Data           APAC    Medium            29.199007
4         Data         Europe  Critical            29.184007
..         ...            ...       ...                  ...
192      Sales    Middle East       Low            37.678676
193      Sales    Middle East    Medium            22.810376
194      Sales  North America      High            29.184007
195      Sales  North America       Low            16.629504
196      Sales  North America    Medium            13.408193

[197 rows x 4 columns]

In [278]:
pm_rank=records.groupby('pm_name')['client_satisfaction'].mean().sort_values(ascending=False).reset_index()

In [279]:
pm_rank['rank']=pm_rank['client_satisfaction'].rank(ascending=False, method='dense')
pm_rank[['pm_name', 'rank']].head()

          pm_name  rank
0  Ahmed Robinson   1.0
1     Amara Clark   1.0
2      Amara Chen   1.0
3     Alex Walker   1.0
4        Chen Ali   1.0

## budget run rate per project type

In [280]:
projects['burn_rate']= projects['actual_spend_usd']/projects['budget_usd']

In [281]:
burn_rate_by_type=(
    projects.groupby('project_type')['burn_rate'].mean().reset_index().sort_values('burn_rate', ascending=False)
)
burn_rate_by_type

         project_type  burn_rate
1     API Integration   0.663615
4  ERP Implementation   0.663169
5  Marketing Campaign   0.652561
9        Web Platform   0.636263
6          Mobile App   0.634726
0         AI/ML Model   0.634375
8      Security Audit   0.626881
7      Product Launch   0.622680
3       Data Pipeline   0.618910
2     Cloud Migration   0.616457

## clients that  cancel the projects

In [299]:
cancelled_projects = projects[projects['status'] == 'Cancelled']

In [300]:
cancel_counts=(
    cancelled_projects.groupby('client').size().reset_index(name='cancel_count').sort_values('cancel_count', ascending=False)
)
cancel_counts

               client  cancel_count
13           NovaCare            24
11          LumaMedia            20
5         Frontier AI            16
10  Keystone Partners            14
7         HorizonBank            14
2     Cornerstone Inc            14
12     Meridian Group            14
1         BlueSky Ltd            13
8          InnovateCo            13
3       Delta Systems            13
0           Apex Corp            12
6          GlobalTech            12
4      Elevate Health            12
14        OmegaRetail            11
9       JetStream LLC             7

In [303]:
records[['salary','team_size','avg_velocity','client_satisfaction']].corr()

                       salary  team_size  avg_velocity  client_satisfaction
salary               1.000000  -0.018359     -0.007275             0.027998
team_size           -0.018359   1.000000      0.023944             0.005993
avg_velocity        -0.007275   0.023944      1.000000            -0.010465
client_satisfaction  0.027998   0.005993     -0.010465             1.000000